### PR TITLE
chore(node): use node 14

### PR DESCRIPTION
**Pull request by adamdehaven**
### Summary

Use node `14.x` instead of `12.x`

### PR Checklist
- [x] Does not introduce dependencies
- [x] **Functional:** all changes do not break existing APIs and if so, bump major version.
- [x] **Tests pass:** check the output of yarn test packages/<Kongponent>
- [x] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
- [x] **Framework style:** abides by the essential rules in Vue's style guide
- [x] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs), or leftover comments
- [ ] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

### CODE REVIEW

**Comment by chrisvdp** [comment]
Looks like you also need to update the `.nvmrc` file. I wonder if we should switch to an approach like https://github.com/actions/setup-node/issues/32#issuecomment-525791142

**Comment by zekth** [comment]
> Looks like you also need to update the `.nvmrc` file. I wonder if we should switch to an approach like [actions/setup-node#32 (comment)](https://github.com/actions/setup-node/issues/32#issuecomment-525791142)

That's the way to do it. +1 on this

**Review by chrisvdp — APPROVED** [review]
nice work on the gh action

**Comment by adamdehaven** [comment]
Could have done it without you @chrisvdp; just wouldn't have been as exciting 😂

**Pull request merged**
