### PR TITLE
fix(kcodeblock): buttons not being bordered in light theme

### PR DESCRIPTION
**Pull request by kleinfreund**
# Summary

Changes the style of buttons inside the code block to have borders in the light theme.

## PR Checklist

* [x] **Conventional Commits** all commits follow the conventional commit standards [outlined in the main README](https://github.com/Kong/kongponents#committing-changes).
* [x] **Tests coverage:** test coverage was added for new features and bug fixes
* [x] **Docs:** includes a technically accurate README

### CODE REVIEW

**Comment by kleinfreund** [comment]
@erickrico I’ve created this PR to show how the light theme of the code block will look with bordered buttons (once the preview of the Kongponents docs site is up and running).

**Comment by erickrico** [comment]
> @erickrico I’ve created this PR to show how the light theme of the code block will look with bordered buttons (see https://deploy-preview-1722--kongponents.netlify.app/components/codeblock.html).

LGTM!, can we increase the padding between the 2 copy buttons a bit (maybe 16px), seems too tight together in this scenario 
Screenshot 2023-09-14 at 12 19 21 p m

**Comment by kleinfreund** [comment]
> can we increase the padding between the 2 copy buttons a bit (maybe 16px), seems too tight together in this scenario Screenshot 2023-09-14 at 12 19 21 p m

Done. I’ve changed this from 4px to 8px (16px seemed too excessive). Let me know if that’s good for you.

**Comment by adamdehaven** [comment]
image
Is it intentional that two of the buttons have a blue border, and the navigation buttons are gray?

**Comment by kleinfreund** [comment]
> Is it intentional that two of the buttons have a blue border, and the navigation buttons are gray?

I think, yes, because the two other buttons are initially disabled. Typing in a query will give them the same appearance. That being said, I don’t have strong opinions about whether the enabled buttons should have that border or not. That’s generally true for the appearance of buttons here as they’re kind of falling out the well-established button appearances.

**Review by adamdehaven — APPROVED** [review]
lgtm

**Comment by Sesay081** [comment]
What about trouble shooting

**Pull request merged**
