### PR TITLE
fix(kslideout): tooltip content being cut-off

### PR DESCRIPTION
**Pull request by kleinfreund**
# Summary

Fix positioned content extending past the slideout’s content area (e.g. tooltips) being cut-off.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

| Before | After |
| ------ | ----- |
| image | image |

## Notes

I tried to avoid introducing an additional element in the markup by using `.content` as the scroll container; however, since this element doesn’t include the header content, the scrollbars would be triggered offset from the top of the viewport.

## PR Checklist

* [x] **Conventional Commits** all commits follow the conventional commit standards [outlined in the main README](https://github.com/Kong/kongponents#committing-changes).
* [x] **Tests coverage:** test coverage was added for new features and bug fixes
* [x] **Docs:** includes a technically accurate README

### CODE REVIEW

**Comment by adamdehaven** [comment]
This PR isn't needed, you just need to add the `position-fixed` prop to the `KTooltip`

```vue
<KTooltip
  label="Tooltip overflowing the slideout content area"
  placement="left"
  position-fixed
>
  <KButton appearance="primary">Buttons</KButton>
</KTooltip>
```

image

**Comment by kleinfreund** [comment]
> This PR isn't needed, you just need to add the `position-fixed` prop to the `KTooltip`

That does address the issue sufficiently for uses of KTooltip/KPop indeed.

Wouldn’t it still be nice from it even occurring in KSlideout in the first place? Application components could also have positioned content that would need similar workarounds.

**Comment by adamdehaven** [comment]
I'm still not sure this is a viable solution; this double-scrollbar isn't ideal
image

**Comment by kleinfreund** [comment]
> I'm still not sure this is a viable solution; this double-scrollbar isn't ideal

The double scrollbar is unavoidable in fixed positioned content that overflows vertically. That’s also the behavior of KSlideout today.

**Comment by kleinfreund** [comment]
Closing this as it was superseded by https://github.com/Kong/kongponents/pull/2012.

**Pull request closed without merging**
