### PR TITLE
feat(kicon): add new cloud-hybrid icon

### PR DESCRIPTION
**Pull request by dustinryerson**
# Summary

Adds new icon `cloudHybrid`:

Screenshot 2023-02-07 at 3 51 09 PM

## PR Checklist

* [x] Does not introduce dependencies
* [x] **Functional:** all changes do not break existing APIs and if so, bump major version.
* [x] **Tests pass:** check the output of yarn test
* [x] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
* [x] **Framework style:** abides by the essential rules in Vue's style guide
* [x] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs, debugger), or leftover comments
* [x] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

### CODE REVIEW

**Review by adamdehaven — COMMENTED** [review]
The code looks good. Does it make sense to name as something more generic? (I have zero suggestions lol)

**Comment by dustinryerson** [comment]
> The code looks good. Does it make sense to name as something more generic? (I have zero suggestions lol)

I think that would make sense, how about either `hybrid` or `hostedService`?

**Review by adamdehaven — DISMISSED** [review]
Not blocking for the name, but yeah does cloud hybrid or something make sense? 🤷🏼 

Your call, I have no preference just thinking some of the icons are so specific lol

**Comment by dustinryerson** [comment]
> Not blocking for the name, but yeah does cloud hybrid or something make sense? 🤷🏼
> 
> Your call, I have no preference just thinking some of the icons are so specific lol

I think it's a good idea, I've renamed to `cloudHybrid`:

Screenshot 2023-02-07 at 4 36 28 PM

**Review by adamdehaven — APPROVED** [review]

**Pull request merged**
