### PR TITLE
feat(KIcon): Adds filter, forward arrow, and table icons

### PR DESCRIPTION
**Pull request by kaiarrowood**
### Summary
Add new KIcons

#### Changes made:
Added the following icons
* filter
* forward arrow
* table

### PR Checklist
- [x] Does not introduce dependencies
- [x] **Functional:** all changes do not break existing APIs and if so, bump major version.
- [x] **Tests pass:** check the output of yarn test packages/<Kongponent>
- [x] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
- [x] **Framework style:** abides by the essential rules in Vue's style guide
- [x] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs), or leftover comments
- [x] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

### CODE REVIEW

**Comment by kaiarrowood** [comment]
@erickrico It looks like the arrow provided is facing the wrong direction, could you send the reversed image?
Also, as mentioned by @travispamaral, could you modify the table icon to be the same color as the others?

**Comment by kaiarrowood** [comment]
@travispamaral I was looking through the code trying to figure out how your docs get updated, but could not tell where in the code to look to get the docs to display the new icons.

**Comment by travispamaral** [comment]
You can run the docs by running `yarn docs:dev`. The new icons should show to automatically as long as the exist in the `icons/index.js` file.

**Comment by kaiarrowood** [comment]
Thanks Travis, I figured it out a moment before you replied!

**Comment by kaiarrowood** [comment]
@erickrico Thanks to some help from Travis I was able to figure out how to modify the SVGs myself and fix the mentioned issues above myself, so nothing else should be needed.

**Pull request merged**
