### PR TITLE
feat(KIcon): Add Shared Config icon

### PR DESCRIPTION
**Pull request by kaiarrowood**
### Summary
Add Shared Config icon

#### Changes made:
* Add Shared Config icon

image

### PR Checklist
- [x] Does not introduce dependencies
- [x] **Functional:** all changes do not break existing APIs and if so, bump major version.
- [x] **Tests pass:** check the output of yarn test packages/<Kongponent>
- [x] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
- [x] **Framework style:** abides by the essential rules in Vue's style guide
- [x] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs), or leftover comments
- [x] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

### CODE REVIEW

**Comment by darrenjennings** [comment]
I toggled the viewbox. Should the viewbox not have padding or the icon be centered within it?
image

**Comment by steph-kalacis** [comment]
> I toggled the viewbox. Should the viewbox not have padding or the icon be centered within it?
> image

If the padding is required the icon should be centered within it.

**Comment by steph-kalacis** [comment]
The icon is darker than the rest of the nav icons (connections, services). Can you confirm what color it is?

**Comment by kaiarrowood** [comment]
@steph-kalacis I got the SVG from @erickrico - can someone give me the one design would like us to use?

**Comment by kaiarrowood** [comment]
@darrenjennings @steph-kalacis Got the icon from Erick and should be able to review now!

**Review by steph-kalacis — APPROVED** [review]

**Review by darrenjennings — APPROVED** [review]

**Pull request merged**
